<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1466152530007" stop="1466152541412">
    <name>Default Suite</name>
    <test-cases>
        <test-case start="1466152530845" stop="1466152541388" status="broken">
            <name>feature[Groups]</name>
            <failure>
                <message>CucumberException: java.lang.AssertionError: 
Expected: &lt;[GroupData{id=2, name='test name'}, GroupData{id=1, name='Test group modified'}, GroupData{id=2147483647, name='xxx'}]&gt;
     but: was &lt;[GroupData{id=2, name='test name'}, GroupData{id=1, name='Test group modified'}, GroupData{id=3, name='xxx'}]&gt;</message>
                <stack-trace>cucumber.runtime.CucumberException: java.lang.AssertionError: 
Expected: &lt;[GroupData{id=2, name='test name'}, GroupData{id=1, name='Test group modified'}, GroupData{id=2147483647, name='xxx'}]&gt;
     but: was &lt;[GroupData{id=2, name='test name'}, GroupData{id=1, name='Test group modified'}, GroupData{id=3, name='xxx'}]&gt;
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.AssertionError: 
Expected: &lt;[GroupData{id=2, name='test name'}, GroupData{id=1, name='Test group modified'}, GroupData{id=2147483647, name='xxx'}]&gt;
     but: was &lt;[GroupData{id=2, name='test name'}, GroupData{id=1, name='Test group modified'}, GroupData{id=3, name='xxx'}]&gt;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at ru.stesting.jtraining.addressbook.bdd.GroupStepDefinitions.verufyGroupCreated(GroupStepDefinitions.java:56)
	at âœ½.Then the new set of groups is equal to the old set with added group(bdd/groups.feature:6)
</stack-trace>
            </failure>
            <steps/>
            <attachments/>
            <labels/>
        </test-case>
    </test-cases>
    <labels/>
</ns2:test-suite>
